# Generated by Django 5.0.7 on 2024-08-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfIncome', models.CharField(max_length=75)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Spendings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfSpending', models.CharField(max_length=75)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
