# Generated by Django 5.0.7 on 2024-08-03 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='nameOfIncome',
            new_name='name',
        ),
    ]
