# Generated by Django 5.0.7 on 2024-08-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_income_name_remove_spendings_nameofspending_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spendings',
            new_name='Spending',
        ),
    ]
