# Generated by Django 5.0.7 on 2024-08-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_spendings_spending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('transactionType', models.CharField(choices=[('I', 'Income'), ('E', 'Expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('expenceType', models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation'), ('housing', 'Housing'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('clothing', 'Clothing'), ('insurance', 'Insurance'), ('savings', 'Savings'), ('miscellaneous', 'Miscellaneous')], max_length=15)),
            ],
        ),
    ]
