# Generated by Django 5.0.7 on 2024-08-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(choices=[('I', 'Income'), ('E', 'Expense')], max_length=1),
        ),
    ]
